### ISSUE TITLE
likelihood and selfing

### ISSUE THREAD

**Issue by thoree** [magnusdv/pedprobr#5]
I don't understand the likelihood below
``` r
library(pedprobr, quietly = T)
z = ped(id = 1:4, fid = c(0, 0, 1, 1), mid = c(0, 0, 2, 1), sex = c(0, 0, 1, 1))
m = marker(z, "1" = 1, "2" = 1, alleles = 1:2)
likelihood(z,m)
#> [1] 0.00390625
```

<sup>Created on 2019-02-06 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by magnusdv** [comment]
Yes, the likelihood computation seems to be broken in pedigrees with selfing. 
Here's the simplest possible example:
``` r
library(pedprobr, quietly = T)

# Simplest possible selfing pedigree: Parent-child
z = ped(id = 1:2, fid = c(0, 1), mid = c(0, 1), sex = c(0, 1))

# Parent and child both homozygous
m = marker(z, "1" = 1, "2" = 1, alleles = 1:2)

# The likelihood should be 1
likelihood(z,m)
#> [1] 0.0625
```

I will look into this when I get round to this package the next time.

**Comment by magnusdv** [comment]
This turned out to be a bit more complicated than I anticipated. For now, the `likelihood()` function now raises an error if the pedigree has selfing.
