### ISSUE TITLE
founder_inbreeding and a pair of linked markers

### ISSUE THREAD

**Issue by thoree** [magnusdv/pedprobr#6]
Apparently the `likelihood` function ignores founder inbreeding
for  a pair of linked markers. This is  probably not trivial to fix, but 
users could be notified:

``` r
library(pedprobr, quietly = TRUE)
x1 = nuclearPed(2)
m1 = marker(x1, "3" = 1, "4" = 2, name = "L1")
m2 = marker(x1, "3" = 1, "4" = 2, name = "L2")
founderInbreeding(x1, 1) = 1
likelihood(x1, m1, m2, theta = 0.01)
#> [1] 0.0009382735
```

<sup>Created on 2019-02-15 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by magnusdv** [comment]
Thanks, this will now (as of d22de5f) raise an error, with a note reminding that the likelihood of linked markers is generally ill-defined in pedigrees with founder inbreeding. 

The cases where this *is* well-defined, e.g. with founder inbreeding $f=1$, will be implemented some time in the future. Feel free to open a new issue if this should be prioritised!
